### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by cassianomon** [vishr/local-history#79]
On my computer at home, my coworkers computer and my computer at work it just doesnt load anymore, if I open command palette on sublime and type "Local" it doesn't show, if I uninstall the plugin and reinstall it doesnt work too...

Tell me if you need any info :)

**Comment by jrappen** [comment]
@cassianomon if you're on Linux, does #81 work for you?

**Comment by cassianomon** [comment]
It's 1 mac and 2 windows also my pc at home is windows

**Comment by jrappen** [comment]
With the latest version?

**Comment by cassianomon** [comment]
Yes, when I saw it was not working (exactly when I most needed hehehe) we tested on the other computers and then I uninstalled in all of them and reinstalled to the last version, it doesnt even show on command palette when I type "Local"

**Comment by cassianomon** [comment]
Nothing on this? I wish I could contribute but I really don't know what to do hehe

**Comment by jrappen** [comment]
is this happening on ST2 or ST3?

**Comment by cassianomon** [comment]
Both, is it working for you? Try uninstall and reinstall the package, because I tried on other computers and it did not worked too.

**Comment by airbornemist6** [comment]
I also see this same behavior on ST2 with the latest version. Currently Trying to screw with it on my machine to see why.

**Comment by jrappen** [comment]
@cassianomon please see if the latest updates resolve your issue, Package Control should update within the next hour or so.

**Comment by cassianomon** [comment]
Now if I type on the command palette if shows the options of Local History, but when I choose one of them (Open, Browse) it do nothing, when I choose "Open" it says "Local history not found for 'index.html'"

**Comment by jrappen** [comment]
Opening and browsing history works both for me.

**Comment by cassianomon** [comment]
On the Windows Sublime Text 2 it opens "Documents" when I select Local History: Open. :/

**Comment by cassianomon** [comment]
On my computer at home (Windows 10/Sublime Text 3) it's working perfectly

**Comment by airbornemist6** [comment]
So, I'm not sure if this is related but I do see this:
```
Exception in thread Thread-28:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\LocalHistory.py", line 119, in process_history
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

And I see it just about every time that an action happens that should trigger a local history backup.

**Comment by Pictor13** [comment]
@Cassiano did you check that in the history-version files are created on save and that are present in the local-history folder?

Taking a look at the source code, *"Local history not found for 'index.html'"* happens when no file has been found in the folder. 

Depending on your settings could be that the plugin is not saving the changes to the ```index.html``` (by default you have to edit the file and **close it**, according to the [```history_on_close``` default setting](https://github.com/vishr/local-history/blob/master/settings/LocalHistory.sublime-settings#L4)).
Also try to disable the ```portable``` option and specify a ```history_path```; then edit your file a couple of time and check if the versions are created under ```~/.sublime/Local History/```.
Also pay attention to eventual messages in the bottom bar (*not* in the console).

**Comment by cassianomon** [comment]
Sup, I am using VSCode now, local history extension working there. Thanks.
