### ISSUE TITLE
Local History: Browse Not working

### ISSUE THREAD

**Issue by jfilter** [vishr/local-history#93]
Hey,

I can open and compare old versions but I cannot use the browse command. It always give me:

FileNotFoundError: [Errno 2] No such file or directory: 'open /Users/filter/Library/Application Support/Sublime Text 3/.sublime/Local History/Users/filter/code/$MY_PROJECT_PATH'

Do you know what the problem is? Thanks for your help!

On my Mac, updated Sublime Text 3

**Comment by txl263** [comment]
Same problem at my Mac. I can find the local history file like this "main-20170520212607.py" but the sublime can not find it.
````
FileNotFoundError: [Errno 2] No such file or directory: 'open /Volumes/MAC_DATA_USB/Eric/.sublime/Local History/Volumes/MAC_DATA_USB/Eric/Documents/$MY_PROJCET_PATH'
````

**Comment by reagle** [comment]
Me too, on mac.

**Comment by BirdyOz** [comment]
+1, on mac

**Comment by reagle** [comment]
I think the error above is because the plugin didn't properly account for (i.e., escape) spaces in the path.

Another problem that could be fixed is to canonicalize paths such that it realize that symlinks can create two paths to the same file.

**Comment by reagle** [comment]
The following change works for me in [line 168](https://github.com/vishr/local-history/blob/master/LocalHistory.py#L168)

`subprocess.call('open %s' % shlex.quote(target_dir), shell=True)`

**Comment by reagle** [comment]
Should I open a new issue for realpath?

**Comment by Pictor13** [comment]
I created a pull request with the fix performed as suggested from the [Python documentation (1st paragraph)](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments):

> Providing a sequence of arguments is generally preferred, as it allows the module to take care of any required escaping and quoting of arguments (e.g. to permit spaces in file names).

**This fixes just on Mac**, and the pull request is just relative to this ticket.

However it should probably be changed also for the execution on _Linux_ and _Windows_, as using ```shell=True``` should be avoided (and as written above, the best method is providing a List of args):

> Executing shell commands that incorporate unsanitized input from an untrusted source makes a program vulnerable to shell injection, a serious security flaw which can result in arbitrary command execution. For this reason, **the use of shell=True is strongly discouraged** in cases where the command string is constructed from external input.

I didn't proceed with the fix for these two because I just had access to a MacBook and couldn't test properly the functionality.
